services:
  - type: web
    name: barberdesk
    runtime: python
    rootDir: barberdesk
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: barberdesk-db
          property: connectionURI
      - key: PYTHON_VERSION
        value: "3.11"

databases:
  - name: barberdesk-db
    plan: free
